export const GET_ALL_CANDIDATES = 'GET_ALL_CANDIDATES';
export const DELETE_CANDIDATE = 'DELETE_CANDIDATE';
export const GET_CANDIDATE_BY_ID = 'GET_CANDIDATE_BY_ID';
export const UPDATE_CANDIDATE = 'UPDATE_CANDIDATE';
export const BULK_CANDIDATES = 'BULK_CANDIDATES';
export const REMOVE_CANDIDATE_FROM_FOLDER = 'REMOVE_CANDIDATE_FROM_FOLDER';