export const GET_ALL_CANDIDATES = 'GET_ALL_CANDIDATES';
export const DELETE_CANDIDATE = 'DELETE_CANDIDATE';
export const CANDIDATE_BY_ID = 'CANDIDATE_BY_ID';
export const CANDIDATE_UPDATE = 'CANDIDATE_UPDATE';
export const BULK_CANDIDATES = 'BULK_CANDIDATES';
