export const GET_DOSSIER = 'GET_DOSSIER';
export const NEW_FOLDER = 'NEW_FOLDER';
export const FOLDER_BY_ID = 'FOLDER_BY_ID';
export const CONFIRM_FOLDER = 'CONFIRM_FOLDER';
export const GET_ALL_FOLDERS = 'GET_ALL_FOLDERS';
export const SET_ACTIVE_FOLDER = 'SET_ACTIVE_FOLDER';
