export const data = [
  {
    id: 1,
    uuid: '7bf995a5-8ef6-4c00-b759-6b4f407b7712',
    opened: true,
    status: 'sent',
    createdAt: '2020-11-15T19:52:09.864Z',
    updatedAt: '2020-11-23T03:24:12.357Z',
    userId: 14,
    recruiterId: 14,
    recruiter: {
      company: 'Jones',
      contactName: 'Carter',
      email: 'Royce_Gutkowski49@gmail.com',
    },
    candidates: [
      {
        id: 1,
        firstName: 'Rowland',
        lastName: 'Zboncak',
        email: 'Barrett_Jacobs23@gmail.com',
        country: 'Latvia',
        cohort: '2',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/matthewkay_/128.jpg',
        visibility: 'listed',
        status: 'unemployed',
        miniBio:
          'Nostrum suscipit et et. Aut odit voluptatem quos. Dolorum ut delectus ut deleniti minus voluptas maiores autem voluptas. Minus quia adipisci modi qui dolor incidunt. Magni sed et enim est sed sed omni',
        linkedin: 'https://gaylord.info',
        github: 'http://mercedes.org',
      },
      {
        id: 2,
        firstName: 'Bennie',
        lastName: 'Skiles',
        email: 'Darby44@hotmail.com',
        country: 'Poland',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/juamperro/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quisquam quos dolores illum adipisci amet quo. Qui sit neque ipsum quam dolore. Ipsam et quia. Dolorum aut ipsa in ipsa.',
        linkedin: 'https://amy.info',
        github: 'https://demetrius.org',
      },
      {
        id: 3,
        firstName: 'Myrl',
        lastName: 'Davis',
        email: 'Fabiola.Swift69@gmail.com',
        country: 'Luxembourg',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/heycamtaylor/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Nam dolorum et quia deserunt sed id. Magnam veniam nihil officia eum ad non. Voluptas ut quia quod. Necessitatibus rerum in. Eligendi corrupti tenetur iusto. Aliquid eveniet eaque.',
        linkedin: 'https://thomas.net',
        github: 'http://mario.net',
      },
      {
        id: 4,
        firstName: 'Jaquelin',
        lastName: 'Mohr',
        email: 'Dominique_Kessler@yahoo.com',
        country: 'Argentina',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/gabrielizalo/128.jpg',
        visibility: 'listed',
        status: 'employed',
        miniBio:
          'Suscipit id voluptatibus odio tenetur facilis error vel. Et reiciendis ipsum sapiente ea. Aperiam facere et rerum illo possimus nihil.',
        linkedin: 'https://dion.biz',
        github: 'https://madelynn.net',
      },
      {
        id: 5,
        firstName: 'Kristoffer',
        lastName: 'Trantow',
        email: 'Ewald.Kovacek@hotmail.com',
        country: 'Montenegro',
        cohort: '7',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/kostaspt/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Debitis corrupti earum quia. Pariatur est iusto quod. Sunt eligendi doloremque qui temporibus vero. Inventore et cupiditate. Architecto nihil aliquam. Assumenda repudiandae sit consectetur quia ut cup',
        linkedin: 'https://piper.biz',
        github: 'https://herbert.org',
      },
    ],
  },
  {
    id: 2,
    uuid: '22775cd0-1ffc-44ab-8560-46214ac0f8a9',
    opened: false,
    status: 'sent',
    createdAt: '2019-12-21T13:08:16.015Z',
    updatedAt: '2020-11-23T14:37:11.557Z',
    userId: 13,
    recruiterId: 13,
    recruiter: {
      company: 'Walter',
      contactName: 'Maximillia',
      email: 'Janessa.Barton60@hotmail.com',
    },
    candidates: [
      {
        id: 1,
        firstName: 'Rowland',
        lastName: 'Zboncak',
        email: 'Barrett_Jacobs23@gmail.com',
        country: 'Latvia',
        cohort: '2',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/matthewkay_/128.jpg',
        visibility: 'listed',
        status: 'unemployed',
        miniBio:
          'Nostrum suscipit et et. Aut odit voluptatem quos. Dolorum ut delectus ut deleniti minus voluptas maiores autem voluptas. Minus quia adipisci modi qui dolor incidunt. Magni sed et enim est sed sed omni',
        linkedin: 'https://gaylord.info',
        github: 'http://mercedes.org',
      },
      {
        id: 2,
        firstName: 'Bennie',
        lastName: 'Skiles',
        email: 'Darby44@hotmail.com',
        country: 'Poland',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/juamperro/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quisquam quos dolores illum adipisci amet quo. Qui sit neque ipsum quam dolore. Ipsam et quia. Dolorum aut ipsa in ipsa.',
        linkedin: 'https://amy.info',
        github: 'https://demetrius.org',
      },
      {
        id: 3,
        firstName: 'Myrl',
        lastName: 'Davis',
        email: 'Fabiola.Swift69@gmail.com',
        country: 'Luxembourg',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/heycamtaylor/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Nam dolorum et quia deserunt sed id. Magnam veniam nihil officia eum ad non. Voluptas ut quia quod. Necessitatibus rerum in. Eligendi corrupti tenetur iusto. Aliquid eveniet eaque.',
        linkedin: 'https://thomas.net',
        github: 'http://mario.net',
      },
      {
        id: 4,
        firstName: 'Jaquelin',
        lastName: 'Mohr',
        email: 'Dominique_Kessler@yahoo.com',
        country: 'Argentina',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/gabrielizalo/128.jpg',
        visibility: 'listed',
        status: 'employed',
        miniBio:
          'Suscipit id voluptatibus odio tenetur facilis error vel. Et reiciendis ipsum sapiente ea. Aperiam facere et rerum illo possimus nihil.',
        linkedin: 'https://dion.biz',
        github: 'https://madelynn.net',
      },
      {
        id: 5,
        firstName: 'Kristoffer',
        lastName: 'Trantow',
        email: 'Ewald.Kovacek@hotmail.com',
        country: 'Montenegro',
        cohort: '7',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/kostaspt/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Debitis corrupti earum quia. Pariatur est iusto quod. Sunt eligendi doloremque qui temporibus vero. Inventore et cupiditate. Architecto nihil aliquam. Assumenda repudiandae sit consectetur quia ut cup',
        linkedin: 'https://piper.biz',
        github: 'https://herbert.org',
      },
    ],
  },
  {
    id: 3,
    uuid: '4ae93244-8f61-423e-a12f-69fbca5d464a',
    opened: true,
    status: 'created',
    createdAt: '2020-02-19T14:31:03.009Z',
    updatedAt: '2020-11-23T16:11:02.300Z',
    userId: 12,
    recruiterId: 12,
    recruiter: {
      company: 'Conroy',
      contactName: 'Branson',
      email: 'Hal60@hotmail.com',
    },
    candidates: [
      {
        id: 1,
        firstName: 'Rowland',
        lastName: 'Zboncak',
        email: 'Barrett_Jacobs23@gmail.com',
        country: 'Latvia',
        cohort: '2',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/matthewkay_/128.jpg',
        visibility: 'listed',
        status: 'unemployed',
        miniBio:
          'Nostrum suscipit et et. Aut odit voluptatem quos. Dolorum ut delectus ut deleniti minus voluptas maiores autem voluptas. Minus quia adipisci modi qui dolor incidunt. Magni sed et enim est sed sed omni',
        linkedin: 'https://gaylord.info',
        github: 'http://mercedes.org',
      },
      {
        id: 2,
        firstName: 'Bennie',
        lastName: 'Skiles',
        email: 'Darby44@hotmail.com',
        country: 'Poland',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/juamperro/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quisquam quos dolores illum adipisci amet quo. Qui sit neque ipsum quam dolore. Ipsam et quia. Dolorum aut ipsa in ipsa.',
        linkedin: 'https://amy.info',
        github: 'https://demetrius.org',
      },
      {
        id: 3,
        firstName: 'Myrl',
        lastName: 'Davis',
        email: 'Fabiola.Swift69@gmail.com',
        country: 'Luxembourg',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/heycamtaylor/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Nam dolorum et quia deserunt sed id. Magnam veniam nihil officia eum ad non. Voluptas ut quia quod. Necessitatibus rerum in. Eligendi corrupti tenetur iusto. Aliquid eveniet eaque.',
        linkedin: 'https://thomas.net',
        github: 'http://mario.net',
      },
      {
        id: 4,
        firstName: 'Jaquelin',
        lastName: 'Mohr',
        email: 'Dominique_Kessler@yahoo.com',
        country: 'Argentina',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/gabrielizalo/128.jpg',
        visibility: 'listed',
        status: 'employed',
        miniBio:
          'Suscipit id voluptatibus odio tenetur facilis error vel. Et reiciendis ipsum sapiente ea. Aperiam facere et rerum illo possimus nihil.',
        linkedin: 'https://dion.biz',
        github: 'https://madelynn.net',
      },
      {
        id: 5,
        firstName: 'Kristoffer',
        lastName: 'Trantow',
        email: 'Ewald.Kovacek@hotmail.com',
        country: 'Montenegro',
        cohort: '7',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/kostaspt/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Debitis corrupti earum quia. Pariatur est iusto quod. Sunt eligendi doloremque qui temporibus vero. Inventore et cupiditate. Architecto nihil aliquam. Assumenda repudiandae sit consectetur quia ut cup',
        linkedin: 'https://piper.biz',
        github: 'https://herbert.org',
      },
    ],
  },
  {
    id: 4,
    uuid: 'c1de940e-58ec-4cfb-b899-5f33adceadb5',
    opened: false,
    status: 'created',
    createdAt: '2020-09-10T09:05:53.977Z',
    updatedAt: '2020-11-23T18:08:38.587Z',
    userId: 11,
    recruiterId: 11,
    recruiter: {
      company: 'McGlynn',
      contactName: 'Joaquin',
      email: 'Thad24@yahoo.com',
    },
    candidates: [
      {
        id: 1,
        firstName: 'Rowland',
        lastName: 'Zboncak',
        email: 'Barrett_Jacobs23@gmail.com',
        country: 'Latvia',
        cohort: '2',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/matthewkay_/128.jpg',
        visibility: 'listed',
        status: 'unemployed',
        miniBio:
          'Nostrum suscipit et et. Aut odit voluptatem quos. Dolorum ut delectus ut deleniti minus voluptas maiores autem voluptas. Minus quia adipisci modi qui dolor incidunt. Magni sed et enim est sed sed omni',
        linkedin: 'https://gaylord.info',
        github: 'http://mercedes.org',
      },
      {
        id: 2,
        firstName: 'Bennie',
        lastName: 'Skiles',
        email: 'Darby44@hotmail.com',
        country: 'Poland',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/juamperro/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quisquam quos dolores illum adipisci amet quo. Qui sit neque ipsum quam dolore. Ipsam et quia. Dolorum aut ipsa in ipsa.',
        linkedin: 'https://amy.info',
        github: 'https://demetrius.org',
      },
      {
        id: 3,
        firstName: 'Myrl',
        lastName: 'Davis',
        email: 'Fabiola.Swift69@gmail.com',
        country: 'Luxembourg',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/heycamtaylor/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Nam dolorum et quia deserunt sed id. Magnam veniam nihil officia eum ad non. Voluptas ut quia quod. Necessitatibus rerum in. Eligendi corrupti tenetur iusto. Aliquid eveniet eaque.',
        linkedin: 'https://thomas.net',
        github: 'http://mario.net',
      },
      {
        id: 4,
        firstName: 'Jaquelin',
        lastName: 'Mohr',
        email: 'Dominique_Kessler@yahoo.com',
        country: 'Argentina',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/gabrielizalo/128.jpg',
        visibility: 'listed',
        status: 'employed',
        miniBio:
          'Suscipit id voluptatibus odio tenetur facilis error vel. Et reiciendis ipsum sapiente ea. Aperiam facere et rerum illo possimus nihil.',
        linkedin: 'https://dion.biz',
        github: 'https://madelynn.net',
      },
      {
        id: 5,
        firstName: 'Kristoffer',
        lastName: 'Trantow',
        email: 'Ewald.Kovacek@hotmail.com',
        country: 'Montenegro',
        cohort: '7',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/kostaspt/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Debitis corrupti earum quia. Pariatur est iusto quod. Sunt eligendi doloremque qui temporibus vero. Inventore et cupiditate. Architecto nihil aliquam. Assumenda repudiandae sit consectetur quia ut cup',
        linkedin: 'https://piper.biz',
        github: 'https://herbert.org',
      },
    ],
  },
  {
    id: 5,
    uuid: 'a11eb690-0044-4163-83ad-14d6188ab023',
    opened: false,
    status: 'sent',
    createdAt: '2020-06-14T13:12:39.902Z',
    updatedAt: '2020-11-23T17:36:11.691Z',
    userId: 10,
    recruiterId: 10,
    recruiter: {
      company: 'Runolfsson',
      contactName: 'Ari',
      email: 'Carmel.Lubowitz69@gmail.com',
    },
    candidates: [
      {
        id: 6,
        firstName: 'Enrico',
        lastName: 'Mertz',
        email: 'Riley.Breitenberg@gmail.com',
        country: 'Svalbard & Jan Mayen Islands',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/renbyrd/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Nesciunt consequatur ea quia eos qui. Laudantium et debitis. Praesentium consequatur nesciunt fugiat corporis ducimus saepe quae officia. Aliquam id sapiente. Enim deleniti omnis eligendi nulla ullam ',
        linkedin: 'https://karen.org',
        github: 'https://jalyn.net',
      },
      {
        id: 7,
        firstName: 'Sebastian',
        lastName: 'Turcotte',
        email: 'Romaine.Kerluke@yahoo.com',
        country: 'Kyrgyz Republic',
        cohort: '2',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/abelcabans/128.jpg',
        visibility: 'listed',
        status: 'employed',
        miniBio:
          'Id nesciunt quisquam quidem voluptate quia ea. Fugiat soluta distinctio voluptate ea eligendi rerum earum. Hic rerum nihil. Iure corporis rerum et occaecati nihil inventore.',
        linkedin: 'https://ezequiel.com',
        github: 'https://emelie.name',
      },
      {
        id: 8,
        firstName: 'Justen',
        lastName: 'Crist',
        email: 'Paris_Paucek95@gmail.com',
        country: 'Colombia',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/kevinjohndayy/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quo molestias expedita impedit et est eius est consequatur. Provident aut quibusdam occaecati sunt ad. Quibusdam et hic voluptas mollitia vel eos veritatis. Dolor velit assumenda et voluptatum soluta ',
        linkedin: 'http://dudley.org',
        github: 'https://vicente.net',
      },
      {
        id: 9,
        firstName: 'Kennith',
        lastName: 'Bins',
        email: 'Chadrick92@gmail.com',
        country: 'Niue',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/cocolero/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Adipisci et non a. Numquam sequi consectetur. Eum molestiae ipsam dicta dicta amet magni magnam. Sint ab accusamus modi quo debitis laboriosam. Error pariatur vitae magnam eligendi sit vel nostrum fug',
        linkedin: 'http://noe.name',
        github: 'https://carolyne.com',
      },
      {
        id: 10,
        firstName: 'Eldon',
        lastName: 'Casper',
        email: 'Serenity79@yahoo.com',
        country: 'Tonga',
        cohort: '1',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/faisalabid/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quia magnam necessitatibus est eius. Alias vitae dolor. Hic iste corrupti consequatur consectetur accusamus debitis quo. Quam qui libero sit quia libero ab molestiae harum architecto.',
        linkedin: 'https://renee.net',
        github: 'https://gayle.com',
      },
    ],
  },
  {
    id: 6,
    uuid: '7c83a5e9-43b1-487f-8e34-998577be82fb',
    opened: false,
    status: 'created',
    createdAt: '2020-05-21T17:41:20.665Z',
    updatedAt: '2020-11-23T00:10:37.841Z',
    userId: 9,
    recruiterId: 9,
    recruiter: {
      company: 'McDermott',
      contactName: 'Salma',
      email: 'Janie.Skiles@gmail.com',
    },
    candidates: [
      {
        id: 6,
        firstName: 'Enrico',
        lastName: 'Mertz',
        email: 'Riley.Breitenberg@gmail.com',
        country: 'Svalbard & Jan Mayen Islands',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/renbyrd/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Nesciunt consequatur ea quia eos qui. Laudantium et debitis. Praesentium consequatur nesciunt fugiat corporis ducimus saepe quae officia. Aliquam id sapiente. Enim deleniti omnis eligendi nulla ullam ',
        linkedin: 'https://karen.org',
        github: 'https://jalyn.net',
      },
      {
        id: 7,
        firstName: 'Sebastian',
        lastName: 'Turcotte',
        email: 'Romaine.Kerluke@yahoo.com',
        country: 'Kyrgyz Republic',
        cohort: '2',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/abelcabans/128.jpg',
        visibility: 'listed',
        status: 'employed',
        miniBio:
          'Id nesciunt quisquam quidem voluptate quia ea. Fugiat soluta distinctio voluptate ea eligendi rerum earum. Hic rerum nihil. Iure corporis rerum et occaecati nihil inventore.',
        linkedin: 'https://ezequiel.com',
        github: 'https://emelie.name',
      },
      {
        id: 8,
        firstName: 'Justen',
        lastName: 'Crist',
        email: 'Paris_Paucek95@gmail.com',
        country: 'Colombia',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/kevinjohndayy/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quo molestias expedita impedit et est eius est consequatur. Provident aut quibusdam occaecati sunt ad. Quibusdam et hic voluptas mollitia vel eos veritatis. Dolor velit assumenda et voluptatum soluta ',
        linkedin: 'http://dudley.org',
        github: 'https://vicente.net',
      },
      {
        id: 9,
        firstName: 'Kennith',
        lastName: 'Bins',
        email: 'Chadrick92@gmail.com',
        country: 'Niue',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/cocolero/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Adipisci et non a. Numquam sequi consectetur. Eum molestiae ipsam dicta dicta amet magni magnam. Sint ab accusamus modi quo debitis laboriosam. Error pariatur vitae magnam eligendi sit vel nostrum fug',
        linkedin: 'http://noe.name',
        github: 'https://carolyne.com',
      },
      {
        id: 10,
        firstName: 'Eldon',
        lastName: 'Casper',
        email: 'Serenity79@yahoo.com',
        country: 'Tonga',
        cohort: '1',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/faisalabid/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quia magnam necessitatibus est eius. Alias vitae dolor. Hic iste corrupti consequatur consectetur accusamus debitis quo. Quam qui libero sit quia libero ab molestiae harum architecto.',
        linkedin: 'https://renee.net',
        github: 'https://gayle.com',
      },
    ],
  },
  {
    id: 7,
    uuid: '8fe9eabb-74d0-4471-b97d-34929e35f1b5',
    opened: false,
    status: 'created',
    createdAt: '2020-04-19T05:04:15.499Z',
    updatedAt: '2020-11-23T08:12:40.486Z',
    userId: 8,
    recruiterId: 8,
    recruiter: {
      company: 'Purdy',
      contactName: 'Dandre',
      email: 'Isac.Thompson@gmail.com',
    },
    candidates: [
      {
        id: 6,
        firstName: 'Enrico',
        lastName: 'Mertz',
        email: 'Riley.Breitenberg@gmail.com',
        country: 'Svalbard & Jan Mayen Islands',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/renbyrd/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Nesciunt consequatur ea quia eos qui. Laudantium et debitis. Praesentium consequatur nesciunt fugiat corporis ducimus saepe quae officia. Aliquam id sapiente. Enim deleniti omnis eligendi nulla ullam ',
        linkedin: 'https://karen.org',
        github: 'https://jalyn.net',
      },
      {
        id: 7,
        firstName: 'Sebastian',
        lastName: 'Turcotte',
        email: 'Romaine.Kerluke@yahoo.com',
        country: 'Kyrgyz Republic',
        cohort: '2',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/abelcabans/128.jpg',
        visibility: 'listed',
        status: 'employed',
        miniBio:
          'Id nesciunt quisquam quidem voluptate quia ea. Fugiat soluta distinctio voluptate ea eligendi rerum earum. Hic rerum nihil. Iure corporis rerum et occaecati nihil inventore.',
        linkedin: 'https://ezequiel.com',
        github: 'https://emelie.name',
      },
      {
        id: 8,
        firstName: 'Justen',
        lastName: 'Crist',
        email: 'Paris_Paucek95@gmail.com',
        country: 'Colombia',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/kevinjohndayy/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quo molestias expedita impedit et est eius est consequatur. Provident aut quibusdam occaecati sunt ad. Quibusdam et hic voluptas mollitia vel eos veritatis. Dolor velit assumenda et voluptatum soluta ',
        linkedin: 'http://dudley.org',
        github: 'https://vicente.net',
      },
      {
        id: 9,
        firstName: 'Kennith',
        lastName: 'Bins',
        email: 'Chadrick92@gmail.com',
        country: 'Niue',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/cocolero/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Adipisci et non a. Numquam sequi consectetur. Eum molestiae ipsam dicta dicta amet magni magnam. Sint ab accusamus modi quo debitis laboriosam. Error pariatur vitae magnam eligendi sit vel nostrum fug',
        linkedin: 'http://noe.name',
        github: 'https://carolyne.com',
      },
      {
        id: 10,
        firstName: 'Eldon',
        lastName: 'Casper',
        email: 'Serenity79@yahoo.com',
        country: 'Tonga',
        cohort: '1',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/faisalabid/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quia magnam necessitatibus est eius. Alias vitae dolor. Hic iste corrupti consequatur consectetur accusamus debitis quo. Quam qui libero sit quia libero ab molestiae harum architecto.',
        linkedin: 'https://renee.net',
        github: 'https://gayle.com',
      },
    ],
  },
  {
    id: 8,
    uuid: 'e8ede3cc-cc3a-4977-b1b2-ce0a9a608f9b',
    opened: true,
    status: 'sent',
    createdAt: '2019-12-04T14:29:05.048Z',
    updatedAt: '2020-11-23T11:14:06.348Z',
    userId: 7,
    recruiterId: 7,
    recruiter: {
      company: 'King',
      contactName: 'Jack',
      email: 'Cory.Towne@hotmail.com',
    },
    candidates: [
      {
        id: 6,
        firstName: 'Enrico',
        lastName: 'Mertz',
        email: 'Riley.Breitenberg@gmail.com',
        country: 'Svalbard & Jan Mayen Islands',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/renbyrd/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Nesciunt consequatur ea quia eos qui. Laudantium et debitis. Praesentium consequatur nesciunt fugiat corporis ducimus saepe quae officia. Aliquam id sapiente. Enim deleniti omnis eligendi nulla ullam ',
        linkedin: 'https://karen.org',
        github: 'https://jalyn.net',
      },
      {
        id: 7,
        firstName: 'Sebastian',
        lastName: 'Turcotte',
        email: 'Romaine.Kerluke@yahoo.com',
        country: 'Kyrgyz Republic',
        cohort: '2',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/abelcabans/128.jpg',
        visibility: 'listed',
        status: 'employed',
        miniBio:
          'Id nesciunt quisquam quidem voluptate quia ea. Fugiat soluta distinctio voluptate ea eligendi rerum earum. Hic rerum nihil. Iure corporis rerum et occaecati nihil inventore.',
        linkedin: 'https://ezequiel.com',
        github: 'https://emelie.name',
      },
      {
        id: 8,
        firstName: 'Justen',
        lastName: 'Crist',
        email: 'Paris_Paucek95@gmail.com',
        country: 'Colombia',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/kevinjohndayy/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quo molestias expedita impedit et est eius est consequatur. Provident aut quibusdam occaecati sunt ad. Quibusdam et hic voluptas mollitia vel eos veritatis. Dolor velit assumenda et voluptatum soluta ',
        linkedin: 'http://dudley.org',
        github: 'https://vicente.net',
      },
      {
        id: 9,
        firstName: 'Kennith',
        lastName: 'Bins',
        email: 'Chadrick92@gmail.com',
        country: 'Niue',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/cocolero/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Adipisci et non a. Numquam sequi consectetur. Eum molestiae ipsam dicta dicta amet magni magnam. Sint ab accusamus modi quo debitis laboriosam. Error pariatur vitae magnam eligendi sit vel nostrum fug',
        linkedin: 'http://noe.name',
        github: 'https://carolyne.com',
      },
      {
        id: 10,
        firstName: 'Eldon',
        lastName: 'Casper',
        email: 'Serenity79@yahoo.com',
        country: 'Tonga',
        cohort: '1',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/faisalabid/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quia magnam necessitatibus est eius. Alias vitae dolor. Hic iste corrupti consequatur consectetur accusamus debitis quo. Quam qui libero sit quia libero ab molestiae harum architecto.',
        linkedin: 'https://renee.net',
        github: 'https://gayle.com',
      },
    ],
  },
  {
    id: 9,
    uuid: 'b5f94186-93c1-45d9-839e-aa770769de01',
    opened: true,
    status: 'created',
    createdAt: '2020-05-08T12:12:22.238Z',
    updatedAt: '2020-11-22T23:21:13.817Z',
    userId: 6,
    recruiterId: 6,
    recruiter: {
      company: 'Mitchell',
      contactName: 'Makenna',
      email: 'Joannie.Flatley@yahoo.com',
    },
    candidates: [
      {
        id: 6,
        firstName: 'Enrico',
        lastName: 'Mertz',
        email: 'Riley.Breitenberg@gmail.com',
        country: 'Svalbard & Jan Mayen Islands',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/renbyrd/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Nesciunt consequatur ea quia eos qui. Laudantium et debitis. Praesentium consequatur nesciunt fugiat corporis ducimus saepe quae officia. Aliquam id sapiente. Enim deleniti omnis eligendi nulla ullam ',
        linkedin: 'https://karen.org',
        github: 'https://jalyn.net',
      },
      {
        id: 7,
        firstName: 'Sebastian',
        lastName: 'Turcotte',
        email: 'Romaine.Kerluke@yahoo.com',
        country: 'Kyrgyz Republic',
        cohort: '2',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/abelcabans/128.jpg',
        visibility: 'listed',
        status: 'employed',
        miniBio:
          'Id nesciunt quisquam quidem voluptate quia ea. Fugiat soluta distinctio voluptate ea eligendi rerum earum. Hic rerum nihil. Iure corporis rerum et occaecati nihil inventore.',
        linkedin: 'https://ezequiel.com',
        github: 'https://emelie.name',
      },
      {
        id: 8,
        firstName: 'Justen',
        lastName: 'Crist',
        email: 'Paris_Paucek95@gmail.com',
        country: 'Colombia',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/kevinjohndayy/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quo molestias expedita impedit et est eius est consequatur. Provident aut quibusdam occaecati sunt ad. Quibusdam et hic voluptas mollitia vel eos veritatis. Dolor velit assumenda et voluptatum soluta ',
        linkedin: 'http://dudley.org',
        github: 'https://vicente.net',
      },
      {
        id: 9,
        firstName: 'Kennith',
        lastName: 'Bins',
        email: 'Chadrick92@gmail.com',
        country: 'Niue',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/cocolero/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Adipisci et non a. Numquam sequi consectetur. Eum molestiae ipsam dicta dicta amet magni magnam. Sint ab accusamus modi quo debitis laboriosam. Error pariatur vitae magnam eligendi sit vel nostrum fug',
        linkedin: 'http://noe.name',
        github: 'https://carolyne.com',
      },
      {
        id: 10,
        firstName: 'Eldon',
        lastName: 'Casper',
        email: 'Serenity79@yahoo.com',
        country: 'Tonga',
        cohort: '1',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/faisalabid/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quia magnam necessitatibus est eius. Alias vitae dolor. Hic iste corrupti consequatur consectetur accusamus debitis quo. Quam qui libero sit quia libero ab molestiae harum architecto.',
        linkedin: 'https://renee.net',
        github: 'https://gayle.com',
      },
    ],
  },
  {
    id: 10,
    uuid: '729cfbff-e741-469f-b3d9-350b21985ddd',
    opened: false,
    status: 'sent',
    createdAt: '2020-08-21T13:44:21.716Z',
    updatedAt: '2020-11-22T23:59:36.098Z',
    userId: 5,
    recruiterId: 5,
    recruiter: {
      company: 'Jacobs',
      contactName: 'Jordan',
      email: 'Constance.Olson@yahoo.com',
    },
    candidates: [
      {
        id: 11,
        firstName: 'Terence',
        lastName: 'Dare',
        email: 'Susie_Wyman5@hotmail.com',
        country: 'Norway',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/_victa/128.jpg',
        visibility: 'listed',
        status: 'unemployed',
        miniBio:
          'Quisquam aut nisi perspiciatis laboriosam aut assumenda ea ad voluptate. Recusandae facere aspernatur. Aspernatur dolore reprehenderit dolorum est.',
        linkedin: 'http://arlie.name',
        github: 'http://wendy.biz',
      },
      {
        id: 12,
        firstName: 'Thurman',
        lastName: 'Reichert',
        email: 'Cristobal_Crist69@hotmail.com',
        country: 'Palestinian Territory',
        cohort: '6',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/jefffis/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'A harum fugiat placeat qui nemo autem eveniet. Soluta ut debitis ut rerum qui ipsum. Voluptate et et. Quod aspernatur deserunt. Aut voluptate ipsum quasi aperiam. Facere quod sunt maiores.',
        linkedin: 'https://clare.biz',
        github: 'http://blanche.name',
      },
      {
        id: 13,
        firstName: 'Chelsie',
        lastName: 'Keebler',
        email: 'Diamond.Armstrong83@gmail.com',
        country: 'Reunion',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/dgclegg/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Dolores mollitia enim quasi recusandae. Nostrum atque assumenda animi reiciendis est pariatur quidem iste. Sequi ipsam dolores blanditiis esse possimus praesentium natus eveniet aperiam. Eaque ut volu',
        linkedin: 'http://domenico.net',
        github: 'https://myrl.info',
      },
      {
        id: 14,
        firstName: 'Reyes',
        lastName: 'Fisher',
        email: 'Vincenza.Zboncak30@gmail.com',
        country: 'Nepal',
        cohort: '1',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/thatonetommy/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quos dolores at deleniti repudiandae facilis ut id cupiditate. Dolorum ut ipsa est autem ea eum consequatur maiores beatae. Omnis sed quidem itaque odit est ducimus et odio eaque. Voluptatem commodi r',
        linkedin: 'http://noel.org',
        github: 'http://cale.org',
      },
      {
        id: 15,
        firstName: 'Kip',
        lastName: 'Hirthe',
        email: 'Blaze74@hotmail.com',
        country: 'Zambia',
        cohort: '5',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/buddhasource/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Quas cumque ipsum enim soluta doloremque nulla. Fugiat alias rerum eaque. Nemo doloremque aut dolorem sint eos officiis.',
        linkedin: 'https://bertha.info',
        github: 'http://henri.name',
      },
    ],
  },
  {
    id: 11,
    uuid: '24eca5a9-21a3-4ee2-9c18-29c0b4906db0',
    opened: true,
    status: 'created',
    createdAt: '2020-10-30T11:15:57.231Z',
    updatedAt: '2020-11-23T03:06:36.621Z',
    userId: 4,
    recruiterId: 4,
    recruiter: {
      company: 'Borer',
      contactName: 'Lizeth',
      email: 'Jared78@yahoo.com',
    },
    candidates: [
      {
        id: 11,
        firstName: 'Terence',
        lastName: 'Dare',
        email: 'Susie_Wyman5@hotmail.com',
        country: 'Norway',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/_victa/128.jpg',
        visibility: 'listed',
        status: 'unemployed',
        miniBio:
          'Quisquam aut nisi perspiciatis laboriosam aut assumenda ea ad voluptate. Recusandae facere aspernatur. Aspernatur dolore reprehenderit dolorum est.',
        linkedin: 'http://arlie.name',
        github: 'http://wendy.biz',
      },
      {
        id: 12,
        firstName: 'Thurman',
        lastName: 'Reichert',
        email: 'Cristobal_Crist69@hotmail.com',
        country: 'Palestinian Territory',
        cohort: '6',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/jefffis/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'A harum fugiat placeat qui nemo autem eveniet. Soluta ut debitis ut rerum qui ipsum. Voluptate et et. Quod aspernatur deserunt. Aut voluptate ipsum quasi aperiam. Facere quod sunt maiores.',
        linkedin: 'https://clare.biz',
        github: 'http://blanche.name',
      },
      {
        id: 13,
        firstName: 'Chelsie',
        lastName: 'Keebler',
        email: 'Diamond.Armstrong83@gmail.com',
        country: 'Reunion',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/dgclegg/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Dolores mollitia enim quasi recusandae. Nostrum atque assumenda animi reiciendis est pariatur quidem iste. Sequi ipsam dolores blanditiis esse possimus praesentium natus eveniet aperiam. Eaque ut volu',
        linkedin: 'http://domenico.net',
        github: 'https://myrl.info',
      },
      {
        id: 14,
        firstName: 'Reyes',
        lastName: 'Fisher',
        email: 'Vincenza.Zboncak30@gmail.com',
        country: 'Nepal',
        cohort: '1',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/thatonetommy/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quos dolores at deleniti repudiandae facilis ut id cupiditate. Dolorum ut ipsa est autem ea eum consequatur maiores beatae. Omnis sed quidem itaque odit est ducimus et odio eaque. Voluptatem commodi r',
        linkedin: 'http://noel.org',
        github: 'http://cale.org',
      },
      {
        id: 15,
        firstName: 'Kip',
        lastName: 'Hirthe',
        email: 'Blaze74@hotmail.com',
        country: 'Zambia',
        cohort: '5',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/buddhasource/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Quas cumque ipsum enim soluta doloremque nulla. Fugiat alias rerum eaque. Nemo doloremque aut dolorem sint eos officiis.',
        linkedin: 'https://bertha.info',
        github: 'http://henri.name',
      },
    ],
  },
  {
    id: 12,
    uuid: 'd5b0e422-c545-46f3-b84e-799cbe733ac2',
    opened: true,
    status: 'created',
    createdAt: '2020-01-23T21:57:54.074Z',
    updatedAt: '2020-11-23T04:34:01.186Z',
    userId: 3,
    recruiterId: 3,
    recruiter: {
      company: 'Senger',
      contactName: 'Devin',
      email: 'Coy.Schamberger82@yahoo.com',
    },
    candidates: [
      {
        id: 11,
        firstName: 'Terence',
        lastName: 'Dare',
        email: 'Susie_Wyman5@hotmail.com',
        country: 'Norway',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/_victa/128.jpg',
        visibility: 'listed',
        status: 'unemployed',
        miniBio:
          'Quisquam aut nisi perspiciatis laboriosam aut assumenda ea ad voluptate. Recusandae facere aspernatur. Aspernatur dolore reprehenderit dolorum est.',
        linkedin: 'http://arlie.name',
        github: 'http://wendy.biz',
      },
      {
        id: 12,
        firstName: 'Thurman',
        lastName: 'Reichert',
        email: 'Cristobal_Crist69@hotmail.com',
        country: 'Palestinian Territory',
        cohort: '6',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/jefffis/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'A harum fugiat placeat qui nemo autem eveniet. Soluta ut debitis ut rerum qui ipsum. Voluptate et et. Quod aspernatur deserunt. Aut voluptate ipsum quasi aperiam. Facere quod sunt maiores.',
        linkedin: 'https://clare.biz',
        github: 'http://blanche.name',
      },
      {
        id: 13,
        firstName: 'Chelsie',
        lastName: 'Keebler',
        email: 'Diamond.Armstrong83@gmail.com',
        country: 'Reunion',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/dgclegg/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Dolores mollitia enim quasi recusandae. Nostrum atque assumenda animi reiciendis est pariatur quidem iste. Sequi ipsam dolores blanditiis esse possimus praesentium natus eveniet aperiam. Eaque ut volu',
        linkedin: 'http://domenico.net',
        github: 'https://myrl.info',
      },
      {
        id: 14,
        firstName: 'Reyes',
        lastName: 'Fisher',
        email: 'Vincenza.Zboncak30@gmail.com',
        country: 'Nepal',
        cohort: '1',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/thatonetommy/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quos dolores at deleniti repudiandae facilis ut id cupiditate. Dolorum ut ipsa est autem ea eum consequatur maiores beatae. Omnis sed quidem itaque odit est ducimus et odio eaque. Voluptatem commodi r',
        linkedin: 'http://noel.org',
        github: 'http://cale.org',
      },
      {
        id: 15,
        firstName: 'Kip',
        lastName: 'Hirthe',
        email: 'Blaze74@hotmail.com',
        country: 'Zambia',
        cohort: '5',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/buddhasource/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Quas cumque ipsum enim soluta doloremque nulla. Fugiat alias rerum eaque. Nemo doloremque aut dolorem sint eos officiis.',
        linkedin: 'https://bertha.info',
        github: 'http://henri.name',
      },
    ],
  },
  {
    id: 13,
    uuid: '7c3a5d82-55ae-4216-bdb1-d1016a8c4a3f',
    opened: false,
    status: 'sent',
    createdAt: '2020-04-17T05:02:52.536Z',
    updatedAt: '2020-11-23T06:18:34.099Z',
    userId: 2,
    recruiterId: 2,
    recruiter: {
      company: 'Hoeger',
      contactName: 'Rosella',
      email: 'Tito_Friesen@hotmail.com',
    },
    candidates: [
      {
        id: 11,
        firstName: 'Terence',
        lastName: 'Dare',
        email: 'Susie_Wyman5@hotmail.com',
        country: 'Norway',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/_victa/128.jpg',
        visibility: 'listed',
        status: 'unemployed',
        miniBio:
          'Quisquam aut nisi perspiciatis laboriosam aut assumenda ea ad voluptate. Recusandae facere aspernatur. Aspernatur dolore reprehenderit dolorum est.',
        linkedin: 'http://arlie.name',
        github: 'http://wendy.biz',
      },
      {
        id: 12,
        firstName: 'Thurman',
        lastName: 'Reichert',
        email: 'Cristobal_Crist69@hotmail.com',
        country: 'Palestinian Territory',
        cohort: '6',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/jefffis/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'A harum fugiat placeat qui nemo autem eveniet. Soluta ut debitis ut rerum qui ipsum. Voluptate et et. Quod aspernatur deserunt. Aut voluptate ipsum quasi aperiam. Facere quod sunt maiores.',
        linkedin: 'https://clare.biz',
        github: 'http://blanche.name',
      },
      {
        id: 13,
        firstName: 'Chelsie',
        lastName: 'Keebler',
        email: 'Diamond.Armstrong83@gmail.com',
        country: 'Reunion',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/dgclegg/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Dolores mollitia enim quasi recusandae. Nostrum atque assumenda animi reiciendis est pariatur quidem iste. Sequi ipsam dolores blanditiis esse possimus praesentium natus eveniet aperiam. Eaque ut volu',
        linkedin: 'http://domenico.net',
        github: 'https://myrl.info',
      },
      {
        id: 14,
        firstName: 'Reyes',
        lastName: 'Fisher',
        email: 'Vincenza.Zboncak30@gmail.com',
        country: 'Nepal',
        cohort: '1',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/thatonetommy/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quos dolores at deleniti repudiandae facilis ut id cupiditate. Dolorum ut ipsa est autem ea eum consequatur maiores beatae. Omnis sed quidem itaque odit est ducimus et odio eaque. Voluptatem commodi r',
        linkedin: 'http://noel.org',
        github: 'http://cale.org',
      },
      {
        id: 15,
        firstName: 'Kip',
        lastName: 'Hirthe',
        email: 'Blaze74@hotmail.com',
        country: 'Zambia',
        cohort: '5',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/buddhasource/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Quas cumque ipsum enim soluta doloremque nulla. Fugiat alias rerum eaque. Nemo doloremque aut dolorem sint eos officiis.',
        linkedin: 'https://bertha.info',
        github: 'http://henri.name',
      },
    ],
  },
  {
    id: 14,
    uuid: '2bc7090f-1b2e-4109-aa94-2df0fbcced3d',
    opened: false,
    status: 'sent',
    createdAt: '2020-11-09T05:25:40.626Z',
    updatedAt: '2020-11-23T09:43:54.141Z',
    userId: 1,
    recruiterId: 1,
    recruiter: {
      company: 'Renner',
      contactName: 'Bernice',
      email: 'Hunter_Crist@yahoo.com',
    },
    candidates: [
      {
        id: 11,
        firstName: 'Terence',
        lastName: 'Dare',
        email: 'Susie_Wyman5@hotmail.com',
        country: 'Norway',
        cohort: '4',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/_victa/128.jpg',
        visibility: 'listed',
        status: 'unemployed',
        miniBio:
          'Quisquam aut nisi perspiciatis laboriosam aut assumenda ea ad voluptate. Recusandae facere aspernatur. Aspernatur dolore reprehenderit dolorum est.',
        linkedin: 'http://arlie.name',
        github: 'http://wendy.biz',
      },
      {
        id: 12,
        firstName: 'Thurman',
        lastName: 'Reichert',
        email: 'Cristobal_Crist69@hotmail.com',
        country: 'Palestinian Territory',
        cohort: '6',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/jefffis/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'A harum fugiat placeat qui nemo autem eveniet. Soluta ut debitis ut rerum qui ipsum. Voluptate et et. Quod aspernatur deserunt. Aut voluptate ipsum quasi aperiam. Facere quod sunt maiores.',
        linkedin: 'https://clare.biz',
        github: 'http://blanche.name',
      },
      {
        id: 13,
        firstName: 'Chelsie',
        lastName: 'Keebler',
        email: 'Diamond.Armstrong83@gmail.com',
        country: 'Reunion',
        cohort: '3',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/dgclegg/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Dolores mollitia enim quasi recusandae. Nostrum atque assumenda animi reiciendis est pariatur quidem iste. Sequi ipsam dolores blanditiis esse possimus praesentium natus eveniet aperiam. Eaque ut volu',
        linkedin: 'http://domenico.net',
        github: 'https://myrl.info',
      },
      {
        id: 14,
        firstName: 'Reyes',
        lastName: 'Fisher',
        email: 'Vincenza.Zboncak30@gmail.com',
        country: 'Nepal',
        cohort: '1',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/thatonetommy/128.jpg',
        visibility: 'unlisted',
        status: 'unemployed',
        miniBio:
          'Quos dolores at deleniti repudiandae facilis ut id cupiditate. Dolorum ut ipsa est autem ea eum consequatur maiores beatae. Omnis sed quidem itaque odit est ducimus et odio eaque. Voluptatem commodi r',
        linkedin: 'http://noel.org',
        github: 'http://cale.org',
      },
      {
        id: 15,
        firstName: 'Kip',
        lastName: 'Hirthe',
        email: 'Blaze74@hotmail.com',
        country: 'Zambia',
        cohort: '5',
        profilePicture:
          'https://s3.amazonaws.com/uifaces/faces/twitter/buddhasource/128.jpg',
        visibility: 'unlisted',
        status: 'employed',
        miniBio:
          'Quas cumque ipsum enim soluta doloremque nulla. Fugiat alias rerum eaque. Nemo doloremque aut dolorem sint eos officiis.',
        linkedin: 'https://bertha.info',
        github: 'http://henri.name',
      },
    ],
  },
];
